const colors = {
  primary: 'bg-blue-600',
  secondary: 'bg-gray-200',
  accent: 'bg-teal-500',
  background: 'bg-white',
  text: 'text-gray-800',
  textLight: 'text-gray-500',
  backgroundBase: 'bg-blue-50',
  backgroundAccent: 'bg-blue-700',
  backgroundLight: 'bg-white',
  backgroundWarning: 'bg-yellow-400',
  backgroundDanger: 'bg-red-400',
  backgroundModal: 'bg-black',
  backgroundButton: 'bg-blue-500',
  backgroundButtonHover: 'hover:bg-blue-800',
  backgroundPaper: 'bg-white',
  backgroundHeader: 'bg-gray-200',
  border: 'border-gray-300',
  success: 'bg-green-500',
  danger: 'bg-red-500',
  warning: 'bg-yellow-500',
  info: 'bg-blue-400',
};

export { colors };